name: Generate Contribution Breakout Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ADICIONE ESTA SEÇÃO DE PERMISSÕES AQUI
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: jathib/generate-breakout-game@v1
        with:
          USER_NAME: "guilhermehenrsilva"

     
      - name: Commit and push the generated game
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update breakout game"
          file_pattern: breakout.svg
